extends:
  - recommended

rules:
  info-contact: off
  no-server-example.com: error
  operation-4xx-response: error
  operation-description: error
  operation-operationId: error
  operation-summary: error
  security-defined: error

